FROM carla-ros-gft:main

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip \
	iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
	pygame
	
CMD ["roslaunch", "carla_ros_bridge", "carla_ros_bridge.launch", "host:=172.17.0.1"]
